/**
 * Course model: turns the race definition in data/course.json into an ordered
 * list of waypoints.
 *
 * This is a deliberate port of `RAR/src/rar/race/rar.py` from the routing
 * project, kept numerically identical (tests/course.test.js checks it against a
 * fixture generated by that Python) so the two tools cannot quietly disagree
 * about where the course goes.
 *
 * Three kinds of mark:
 *   point  - go to this position
 *   gate   - thread the strait between two named islands, rounding neither
 *   round  - pass a named island on a given side
 *
 * An island rounding is an ARC, not a point. A single point can only say "touch
 * this spot", never "go around it": at Stromboli both neighbouring marks bear
 * the same way, so a single offset point degenerates into an out-and-back spike
 * that never actually passes the island.
 */

import { haversineNm, initialBearing, destinationPoint, norm360 } from "./nav.js";

const OPPOSITE = { starboard: "port", port: "starboard" };

/** Where a gate is threaded: the midpoint between the two named islands. */
export function gatePoint(a, b) {
  return { lat: (a.lat + b.lat) / 2, lon: (a.lon + b.lon) / 2 };
}

/**
 * Points tracing the boat's path AROUND an island, on the circle of radius
 * (island radius + margin), entering from `approach` and leaving toward `exit`.
 *
 * Leaving the island to STARBOARD means the boat's bearing from the island
 * centre increases as it goes round; to PORT it decreases. Sweeping from the
 * entry bearing to the exit bearing in that direction automatically takes the
 * long way round whenever the required side demands it. Where approach and exit
 * bear the same way the sweep collapses toward zero, and going "around" then
 * means a full circuit, so it is taken as 360 degrees.
 */
export function roundingArc(island, approach, exit, side, opts) {
  if (!(side in OPPOSITE)) throw new Error(`side must be port or starboard, got ${side}`);
  const { marginNm = 1.5, arcStepDeg = 45, minSweepDeg = 15 } = opts ?? {};
  const centre = { lat: island.lat, lon: island.lon };
  const radius = island.radius_nm + marginNm;
  const thetaIn = initialBearing(centre, approach);
  const thetaOut = initialBearing(centre, exit);
  const rotation = side === "starboard" ? 1 : -1;

  let sweep = norm360(rotation * (thetaOut - thetaIn));
  if (sweep < minSweepDeg) sweep += 360;

  const steps = Math.max(1, Math.ceil(sweep / arcStepDeg));
  const pts = [];
  for (let k = 0; k <= steps; k++) {
    const theta = norm360(thetaIn + (rotation * sweep * k) / steps);
    pts.push(destinationPoint(centre, theta, radius));
  }
  return pts;
}

/**
 * Derive the counterclockwise sequence from the clockwise one: reverse the
 * order and flip every island's side. Gates have no side and are unchanged.
 * Never hand-duplicated, so the two directions cannot drift apart.
 */
export function reverseAndMirror(sequenceCw) {
  return [...sequenceCw].reverse().map((e) =>
    e.island ? { island: e.island, side: OPPOSITE[e.side] } : { ...e }
  );
}

/**
 * Build the ordered waypoint list for a direction.
 *
 * @param {object} config           parsed data/course.json
 * @param {'clockwise'|'counterclockwise'} direction
 * @param {'full'|'cruising'} variant
 * @returns {Array<{name,lat,lon,kind,legNm,island?,side?,arcIndex?,arcTotal?}>}
 */
export function buildCourse(config, direction = "clockwise", variant = "full") {
  if (direction !== "clockwise" && direction !== "counterclockwise")
    throw new Error(`unknown direction ${direction}`);
  const byName = Object.fromEntries(config.islands.map((i) => [i.name, i]));
  const sequenceCw = variant === "full" ? config.sequence_clockwise : config.cruising_clockwise;
  if (!sequenceCw?.length) throw new Error(`no sequence configured for variant ${variant}`);
  const sequence = direction === "clockwise" ? sequenceCw : reverseAndMirror(sequenceCw);

  const opts = {
    marginNm: config.rounding.margin_nm,
    arcStepDeg: config.rounding.arc_step_deg,
    minSweepDeg: config.rounding.min_sweep_deg,
  };
  const start = { lat: config.start_finish.lat, lon: config.start_finish.lon };

  /** Reference position for a sequence entry, used to know which way the boat
   *  leaves a rounding without having to resolve the next mark's own arc. */
  const aimPoint = (entry) => {
    if (entry.island) {
      const i = byName[entry.island];
      return { lat: i.lat, lon: i.lon };
    }
    return gatePoint(byName[entry.gate[0]], byName[entry.gate[1]]);
  };
  // Aim point of the mark AFTER each entry; the finish closes the loop.
  const nextAims = [...sequence.slice(1).map(aimPoint), start];

  const waypoints = [{ ...start, name: config.start_finish.name, kind: "start", legNm: 0 }];
  let prev = start;
  const push = (w) => {
    const legNm = haversineNm(prev, w);
    waypoints.push({ ...w, legNm });
    prev = { lat: w.lat, lon: w.lon };
  };

  sequence.forEach((entry, idx) => {
    const exit = nextAims[idx];
    if (entry.island) {
      const island = byName[entry.island];
      const arc = roundingArc(island, prev, exit, entry.side, opts);
      arc.forEach((p, k) =>
        push({
          ...p,
          name:
            arc.length === 1
              ? `${island.name} (${entry.side})`
              : `${island.name} (${entry.side}) ${k + 1}/${arc.length}`,
          kind: "island_round",
          island: island.name,
          side: entry.side,
          arcIndex: k,
          arcTotal: arc.length,
        })
      );
    } else {
      const [a, b] = entry.gate.map((n) => byName[n]);
      push({ ...gatePoint(a, b), name: `gate (${a.name}-${b.name})`, kind: "gate", gate: [a.name, b.name] });
    }
  });

  push({ ...start, name: `${config.start_finish.name} (finish)`, kind: "finish" });
  return waypoints;
}

/** Total course distance in nautical miles. */
export const totalDistanceNm = (waypoints) =>
  waypoints.slice(1).reduce((sum, w) => sum + w.legNm, 0);

/**
 * Collapse each rounding arc to one row for display, so the leg list reads as
 * "Stromboli (port)" rather than nine near-identical rows. Returns display
 * groups with the arc's own waypoints attached.
 */
export function displayLegs(waypoints) {
  const out = [];
  for (let i = 0; i < waypoints.length; i++) {
    const w = waypoints[i];
    if (w.kind !== "island_round") {
      out.push({ name: w.name, kind: w.kind, target: w, points: [w], distNm: w.legNm });
      continue;
    }
    let j = i + 1;
    while (j < waypoints.length && waypoints[j].kind === "island_round" && waypoints[j].island === w.island) j++;
    const group = waypoints.slice(i, j);
    out.push({
      name: `${w.island} (${w.side})`,
      kind: "island_round",
      island: w.island,
      side: w.side,
      target: group[group.length - 1],
      entry: group[0],
      points: group,
      distNm: group.reduce((s, g) => s + g.legNm, 0),
    });
    i = j - 1;
  }
  return out;
}

/** Ray-casting point-in-polygon, for warning that a mark sits on land. */
export function isOnLand(pt, coastGeoJSON) {
  for (const f of coastGeoJSON.features) {
    const ring = f.geometry.coordinates[0];
    let inside = false;
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const [xi, yi] = ring[i];
      const [xj, yj] = ring[j];
      if (yi > pt.lat !== yj > pt.lat && pt.lon < ((xj - xi) * (pt.lat - yi)) / (yj - yi) + xi)
        inside = !inside;
    }
    if (inside) return f.properties.kind;
  }
  return null;
}
