#!/bin/sh
# Regenerate tests/fixtures_course_python.json — the golden course geometry that
# tests/course.test.js checks js/course.js against.
#
# nearest_water is monkeypatched to the identity on purpose: the Python router
# nudges waypoints off land using a 1-arcmin raster mask, which is too coarse to
# see the 750 m Bocche di Vulcano and shifts that gate ~550 m. This app uses
# precise OSM coastline instead, so the fixture must capture the pure course
# GEOMETRY; "is it on water" is asserted separately against the better data.
#
# Usage:  tools/build_course_fixture.sh [path/to/sailing_routing/RAR]
set -e
RAR="${1:-$(dirname "$0")/../../sailing_routing/RAR}"
cd "$RAR"
./.venv/bin/python - <<'PY'
import sys, json; sys.path.insert(0, 'src')
import rar.race.rar as R
R.nearest_water = lambda lat, lon: (lat, lon)
from rar.race.rar import RaceConfig, Course
cfg = RaceConfig.load('configs/rar2026.yaml'); c = Course(cfg)
out = {}
for d in ('clockwise', 'counterclockwise'):
    wps = c.build(d)
    out[d] = [{'name': w.name, 'lat': w.lat, 'lon': w.lon, 'kind': w.kind,
               'leg_nm': w.leg_distance_nm} for w in wps]
    print('%-18s %2d wps  %.4f nm' % (d, len(wps), Course.total_distance_nm(wps)))
out['_note'] = ('Generated by RAR/src/rar/race/rar.py Course.build() with nearest_water '
                'monkeypatched to the identity: pure course geometry, no land-mask nudging. '
                'Regenerate with tools/build_course_fixture.sh')
import os
dest = os.path.join(os.path.dirname(__file__), 'fixtures_course_python.json')
json.dump(out, open(sys.argv[1] if len(sys.argv) > 1 else
                    '../../rar-nav/tests/fixtures_course_python.json', 'w'), indent=1)
print('fixture written')
PY
